services:
  database:
    container_name: "tech-challenge2"
    image: "postgres:16.3-alpine3.19"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  db:
    driver: local
  pgadmin:
    driver: local

networks:
  app-network:
    driver: bridge
